# Generated by Django 5.1.4 on 2026-08-06 09:32

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import growth.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="industry"
                    ),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, verbose_name="website URL"),
                ),
                (
                    "target_audience",
                    models.TextField(blank=True, verbose_name="target audience"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="location"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="IANA timezone; all scheduling is rendered in this zone.",
                        max_length=64,
                        validators=[growth.models.validate_timezone],
                        verbose_name="timezone",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="settings"),
                ),
                (
                    "publishing_paused",
                    models.BooleanField(
                        default=False, verbose_name="publishing paused"
                    ),
                ),
                (
                    "replies_paused",
                    models.BooleanField(
                        default=False, verbose_name="auto-replies paused"
                    ),
                ),
                (
                    "review_buffer_hours",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Hours a generated post waits in the calendar before publishing.",
                        verbose_name="review buffer (hours)",
                    ),
                ),
                (
                    "monthly_budget_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Hard cap on LLM/image spend per month.",
                        max_digits=8,
                        verbose_name="monthly budget (USD)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="businesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "business",
                "verbose_name_plural": "businesses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("user", "User"),
                            ("system", "System"),
                        ],
                        max_length=20,
                        verbose_name="actor",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="action")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="payload"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="growth.business",
                        verbose_name="business",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log entry",
                "verbose_name_plural": "audit log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-created_at"],
                        name="growth_audi_busines_258f4b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("instagram", "Instagram"), ("facebook", "Facebook")],
                        max_length=20,
                        verbose_name="platform",
                    ),
                ),
                (
                    "composio_connected_account_id",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Composio connected account id",
                    ),
                ),
                (
                    "external_account_id",
                    models.CharField(
                        blank=True,
                        help_text="Instagram user id or Facebook Page id.",
                        max_length=128,
                        verbose_name="external account id",
                    ),
                ),
                (
                    "external_account_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="external account name"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("healthy", "Healthy"),
                            ("needs_reauth", "Needs reauth"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last checked at"
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="last error")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="growth.business",
                        verbose_name="business",
                    ),
                ),
            ],
            options={
                "verbose_name": "social connection",
                "verbose_name_plural": "social connections",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "platform"), name="unique_business_platform"
                    )
                ],
            },
        ),
    ]
